/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myjni_MyLib */

#ifndef _Included_com_example_myjni_MyLib
#define _Included_com_example_myjni_MyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myjni_MyLib
 * Method:    Setcallback
 * Signature: (Lcom/example/myjni/IMtcCallback;)V
 */
JNIEXPORT void JNICALL Java_com_example_myjni_MyLib_Setcallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_myjni_MyLib
 * Method:    GetDemoString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myjni_MyLib_GetDemoString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
