/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myjni_LoginCtrl */

#ifndef _Included_com_example_myjni_LoginCtrl
#define _Included_com_example_myjni_LoginCtrl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myjni_LoginCtrl
 * Method:    LogoutApsServerCmd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_myjni_LoginCtrl_LogoutApsServerCmd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
