/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_example_myndk_JNITest.h>


extern "C" JNIEXPORT jstring JNICALL
Java_com_example_myndk_JNITest_sayHello(
        JNIEnv* env,
        jobject /* this */) {
    return env->NewStringUTF("Hello from C++");
}
